kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-on-k8s
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.yaml: |-
    bean:
      message: "Message from configMap ...renew #1"
