kind: Secret
apiVersion: v1
metadata:
  name: mongo
  namespace: largemodel-dev
  labels:
    spring.cloud.kubernetes.secret: "true"
data:
  password: eXY5Y2dsaGVieUV2VkFKVQ==
  username: Y29yZQ==
type: Opaque
